# Generated by Django 3.1.1 on 2023-10-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('message', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
